# 构建设置
[build]
  publish = "public/"

# 函数设置
[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/v1beta/*"
  to = "/.netlify/functions/handler"  # <--- 修改这一行
  status = 200
  force = true
