# 构建设置
[build]
  publish = "public/"

# 告诉 Netlify 函数代码在哪个目录下
[functions]
  directory = "api/"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/gemini"
  status = 200
