# netlify.toml

# 构建设置
[build]
  publish = "public/"

# 告诉Netlify，您的云函数位于 "api/" 目录
[functions]
  directory = "api/"

# 路由规则：将所有对 /v1/* 的请求都转发给名为 'handler' 的函数处理
[[redirects]]
  from = "/v1/*"
  to = "/.netlify/functions/handler"
  status = 200
